<?php

/**
 * Imap settings.
 */

defined('ABSPATH') || exit;

class Mapbd_wps_imap_settings extends ApbdWpsModel
{
    public $id;
    public $title;
    public $wps_host;
    public $wps_port;
    public $secure_protocol;
    public $secure_protocol_type;
    public $user_email;
    public $user_password;
    public $send_from;
    public $from_email;
    public $use_title;
    public $attach_with;
    public $choose_category;
    public $status;
    public $cron_cmd;
    // @ Dynamic
    public $tickets_count;
    public $action;


    /**
     *@property id,title,cat_ids,rule_type,rule_id,status
     */
    function __construct()
    {
        parent::__construct();
        $this->SetValidation();
        $this->tableName = "apbd_wps_imap_settings";
        $this->primaryKey = "id";
        $this->uniqueKey = array();
        $this->multiKey = array();
        $this->autoIncField = array("id");
        $this->app_base_name = "support-genix-lite";
    }


    function SetValidation()
    {
        $this->validations = array(
            "id" => array("Text" => "Id", "Rule" => "max_length[11]|integer"),
            "title" => array("Text" => "Title", "Rule" => "max_length[255]"),
            "wps_host" => array("Text" => "Host", "Rule" => "max_length[100]"),
            "wps_port" => array("Text" => "Port", "Rule" => "max_length[100]"),
            "secure_protocol" => array("Text" => "Secure Protocol", "Rule" => "max_length[1]"),
            "secure_protocol_type" => array("Text" => "Secure Protocol Type", "Rule" => "max_length[1]"),
            "user_email" => array("Text" => "User Email", "Rule" => "max_length[100]"),
            "user_password" => array("Text" => "User Password", "Rule" => "max_length[255]"),
            "send_from" => array("Text" => "Send From", "Rule" => "max_length[1]"),
            "from_email" => array("Text" => "From Email", "Rule" => "max_length[255]"),
            "use_title" => array("Text" => "Use Title", "Rule" => "max_length[1]"),
            "attach_with" => array("Text" => "attach with", "Rule" => "max_length[1]"),
            "choose_category" => array("Text" => "choose category", "Rule" => "max_length[255]"),
            "status" => array("Text" => "Status", "Rule" => "max_length[1]"),
            "cron_cmd" => array("Text" => "Corn Command", "Rule" => "max_length[255]"),

        );
    }

    public function GetPropertyRawOptions($property, $isWithSelect = false)
    {
        $returnObj = array();
        switch ($property) {
            case "secure_protocol_type":
                $returnObj = array("S" => "SSL", "T" => "TLS", "A" => "START-TLS");
                break;
            case "secure_protocol":
                $returnObj = array("A" => "Active", "I" => "Inactive");
                break;
            case "status":
                $returnObj = array("A" => "Active", "I" => "Inactive");
                break;
            default:
        }
        if ($isWithSelect) {
            return array_merge(array("" => "Select"), $returnObj);
        }
        return $returnObj;
    }

    public function GetPropertyOptionsColor($property)
    {
        $returnObj = array();
        switch ($property) {
            case "status":
                $returnObj = array("A" => "success", "S" => "success", "N" => "success");
                break;
            default:
        }
        return $returnObj;
    }

    public function GetPropertyOptionsIcon($property)
    {
        $returnObj = array();
        switch ($property) {
            case "rule_type":
                $returnObj = array("A" => "fa fa-check-circle-o", "S" => "fa fa-check-circle-o", "N" => "fa fa-bell");
                break;
            default:
        }
        return $returnObj;
    }
    public function Update($notLimit = false, $isShowMsg = true, $dontProcessIdWhereNotset = true)
    {
        return parent::Update($notLimit, $isShowMsg, $dontProcessIdWhereNotset); // TODO: Change the autogenerated stub
    }

    public function SetFromPostData($isNew = false, $data = null)
    {
        $newData = [];

        $title = sanitize_text_field(ApbdWps_PostValue('title', ''));
        $wps_host = sanitize_text_field(ApbdWps_PostValue('wps_host', ''));
        $wps_port = sanitize_text_field(ApbdWps_PostValue('wps_port', ''));
        $user_email = sanitize_email(ApbdWps_PostValue('user_email', ''));
        $user_password = strval(ApbdWps_PostValue('user_password', ''));
        $secure_protocol = sanitize_text_field(ApbdWps_PostValue('secure_protocol', ''));
        $secure_protocol_type = sanitize_text_field(ApbdWps_PostValue('secure_protocol_type', ''));
        $send_from = sanitize_text_field(ApbdWps_PostValue('send_from', ''));
        $from_email = sanitize_email(ApbdWps_PostValue('from_email', ''));
        $use_title = sanitize_text_field(ApbdWps_PostValue('use_title', ''));
        $attach_with = sanitize_text_field(ApbdWps_PostValue('attach_with', ''));
        $choose_category = absint(ApbdWps_PostValue('choose_category', ''));
        $status = sanitize_text_field(ApbdWps_PostValue('status', ''));

        $send_from = in_array($send_from, array("U", "D")) ? $send_from : "U";
        $use_title = 'Y' === $use_title ? 'Y' : 'N';
        $secure_protocol = 'A' === $secure_protocol ? 'A' : 'I';
        $attach_with = 'A' === $attach_with ? 'A' : 'I';
        $choose_category = strval($choose_category);
        $status = 'A' === $status ? 'A' : 'I';
        $secure_protocol_type = in_array($secure_protocol_type, ['S', 'T', 'A'], true) ? $secure_protocol_type : 'S';

        $from_email = '';

        if (
            (1 > strlen($title)) ||
            (1 > strlen($wps_host)) ||
            (1 > strlen($wps_port)) ||
            (1 > strlen($user_email)) ||
            (1 > strlen($user_password))
        ) {
            return;
        }

        $newData['title'] = $title;
        $newData['wps_host'] = $wps_host;
        $newData['wps_port'] = $wps_port;
        $newData['user_email'] = $user_email;
        $newData['user_password'] = $user_password;
        $newData['secure_protocol'] = $secure_protocol;
        $newData['send_from'] = $send_from;
        $newData['from_email'] = $from_email;
        $newData['use_title'] = $use_title;
        $newData['attach_with'] = $attach_with;
        $newData['status'] = $status;

        if ('A' === $secure_protocol) {
            $newData['secure_protocol_type'] = $secure_protocol_type;
        } elseif ($isNew) {
            $newData['secure_protocol_type'] = 'S';
        }

        if ('A' === $attach_with) {
            if (empty($choose_category)) {
                return;
            }

            $newData['choose_category'] = $choose_category;
        }

        return parent::SetFromPostData($isNew, $newData);
    }

    /**
     * From version 1.4.4
     */
    static function UpdateDBTableCharset()
    {
        $thisObj = new static();
        $table_name = $thisObj->db->prefix . $thisObj->tableName;
        $charset = $thisObj->db->charset;
        $collate = $thisObj->db->collate;

        $alter_query = "ALTER TABLE `{$table_name}` CONVERT TO CHARACTER SET {$charset} COLLATE {$collate}";

        $thisObj->db->query($alter_query);
    }

    /**
     * From version 1.4.23
     */
    static function UpdateDBTable()
    {
        $thisObj = new static();

        $table = $thisObj->db->prefix . $thisObj->tableName;

        if ($thisObj->db->get_var("show tables like '{$table}'") == $table) {
            $thisObj->DBColumnAddOrModify('title', 'char', 255, '', 'NOT NULL', 'id');
            $thisObj->DBColumnAddOrModify('send_from', 'char', 1, '', 'NOT NULL', 'user_password', 'radio(U=User,D=Default)');
            $thisObj->DBColumnAddOrModify('from_email', 'char', 255, '', 'NOT NULL', 'send_from');
            $thisObj->DBColumnAddOrModify('use_title', 'char', 1, '', 'NOT NULL', 'from_email', 'bool(Y=Yes,N=No)');
            $thisObj->db->query("UPDATE `{$table}` SET `title` = `user_email`");
            $thisObj->db->query("UPDATE `{$table}` SET `send_from` = 'D'");
            $thisObj->db->query("UPDATE `{$table}` SET `use_title` = 'N'");
        }
    }

    static function CreateDBTable()
    {
        $thisObj = new static();
        $table = $thisObj->db->prefix . $thisObj->tableName;
        $charsetCollate = $thisObj->db->has_cap('collation') ? $thisObj->db->get_charset_collate() : '';

        if ($thisObj->db->get_var("show tables like '{$table}'") != $table) {
            $sql = "CREATE TABLE `{$table}` (
                      `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                      `title` char(255) NOT NULL DEFAULT '',
                      `wps_host` char(100) DEFAULT '',
                      `wps_port` char(100) NOT NULL DEFAULT '',
                      `secure_protocol` char(1) NOT NULL COMMENT 'bool(A=Active,I=Inactive)',
                      `secure_protocol_type` char(1) NOT NULL COMMENT 'radio(S=SSL,T=TLS)',
                      `user_email` char(100) NOT NULL DEFAULT '',
                      `user_password` char(200) NOT NULL,
                      `send_from` char(1) NOT NULL DEFAULT '' COMMENT 'radio(U=User,D=Default)',
                      `from_email` char(255) NOT NULL DEFAULT '',
                      `use_title` char(1) NOT NULL DEFAULT '' COMMENT 'bool(Y=Yes,N=No)',
                      `attach_with` char(1) NOT NULL COMMENT 'bool(A=Active,I=Inactive)',
                      `choose_category` char(255) NOT NULL,
                      `status` char(1) NOT NULL COMMENT 'bool(A=Active,I=Inactive)',
                      `cron_cmd` char(255) NOT NULL,
                      PRIMARY KEY (`id`)
                    ) $charsetCollate;";
            require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
            dbDelta($sql);
        }
    }
    function DropDBTable()
    {
        global $wpdb;

        $table_name = $wpdb->prefix . $this->tableName;
        $wpdb->query("DROP TABLE IF EXISTS `" . esc_sql($table_name) . "`");
    }
    static function DeleteById($id)
    {
        return  parent::DeleteByKeyValue("id", $id);
    }

    static function CheckDuplicate($mailboxObj, $user_email = '', $status = '', $id = 0)
    {
        $is_duplicate = false;

        $mailbox_id = absint($id);
        $mailbox_email = '';
        $mailbox_status = '';

        if (!empty($mailboxObj)) {
            $mailbox_email = sanitize_email($mailboxObj->user_email);
            $mailbox_status = sanitize_text_field($mailboxObj->status);
        } elseif (!empty($user_email)) {
            $mailbox_email = sanitize_email($user_email);
            $mailbox_status = sanitize_text_field($status);
        }

        if (
            !empty($mailbox_email) &&
            ('A' === $mailbox_status)
        ) {
            $mainObj = new Mapbd_wps_imap_settings();
            $mainObj->user_email($mailbox_email);
            $mainObj->id("!= '{$mailbox_id}'", true);
            $mainObj->status('A');

            if ($mainObj->Select()) {
                $is_duplicate = true;
            } else {
                $mainObj = new Mapbd_wps_imap_api_settings();
                $mainObj->connected_email($mailbox_email);
                $mainObj->id("!= '{$mailbox_id}'", true);
                $mainObj->status('A');

                if ($mainObj->Select()) {
                    $is_duplicate = true;
                }
            }
        }

        return $is_duplicate;
    }
}
