<?php

/**
 * Imap API settings.
 */

defined('ABSPATH') || exit;

class Mapbd_wps_imap_api_settings extends ApbdWpsModel
{
    public $id;
    public $title;
    public $email;
    public $connected_email;
    public $send_from;
    public $from_email;
    public $use_title;
    public $attach_with;
    public $choose_category;
    public $privacy_policy;
    public $secret_key;
    public $status;
    // @ Dynamic
    public $tickets_count;
    public $action;

    /**
     * @property id,title,email,connected_email,send_from,from_email,use_title,attach_with,choose_category,privacy_policy,status
     */
    function __construct()
    {
        parent::__construct();

        $this->SetValidation();

        $this->tableName = "apbd_wps_imap_api_settings";
        $this->primaryKey = "id";
        $this->uniqueKey = array();
        $this->multiKey = array();
        $this->autoIncField = array("id");
        $this->app_base_name = "support-genix-lite";
    }

    function SetValidation()
    {
        $this->validations = array(
            "id" => array("Text" => "Id", "Rule" => "max_length[11]|integer"),
            "title" => array("Text" => "Mailbox Title", "Rule" => "max_length[255]"),
            "email" => array("Text" => "Mailbox Address", "Rule" => "max_length[255]"),
            "connected_email" => array("Text" => "Connected Email Address", "Rule" => "max_length[255]"),
            "send_from" => array("Text" => "Send From", "Rule" => "max_length[1]"),
            "from_email" => array("Text" => "From Email", "Rule" => "max_length[255]"),
            "use_title" => array("Text" => "Use Title", "Rule" => "max_length[1]"),
            "attach_with" => array("Text" => "Attach with", "Rule" => "max_length[1]"),
            "choose_category" => array("Text" => "Choose Category", "Rule" => "max_length[255]"),
            "privacy_policy" => array("Text" => "Privacy Policy", "Rule" => "max_length[1]"),
            "secret_key" => array("Text" => "Secret Key", "Rule" => "max_length[255]"),
            "status" => array("Text" => "Status", "Rule" => "max_length[1]"),
        );
    }

    public function GetPropertyRawOptions($property, $isWithSelect = false)
    {
        $returnObj = array();

        switch ($property) {
            case "status":
                $returnObj = array("A" => "Active", "I" => "Inactive");
                break;

            default:
        }

        if ($isWithSelect) {
            return array_merge(array("" => "Select"), $returnObj);
        }

        return $returnObj;
    }

    public function GetPropertyOptionsColor($property)
    {
        $returnObj = array();

        switch ($property) {
            case "status":
                $returnObj = array("A" => "success", "S" => "success", "N" => "success");
                break;

            default:
        }

        return $returnObj;
    }

    public function GetPropertyOptionsIcon($property)
    {
        $returnObj = array();

        switch ($property) {
            case "rule_type":
                $returnObj = array("A" => "fa fa-check-circle-o", "S" => "fa fa-check-circle-o", "N" => "fa fa-bell");
                break;

            default:
        }

        return $returnObj;
    }

    public function Update($notLimit = false, $isShowMsg = true, $dontProcessIdWhereNotset = true)
    {
        return parent::Update($notLimit, $isShowMsg, $dontProcessIdWhereNotset); // TODO: Change the autogenerated stub
    }

    public function get_domain()
    {
        if (function_exists("site_url")) {
            return site_url();
        }

        if (defined("WPINC") && function_exists("get_bloginfo")) {
            return home_url();
        } else {
            $base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
            $base_url .= "://" . $_SERVER['HTTP_HOST'];
            $base_url .= str_replace(basename($_SERVER['SCRIPT_NAME']), "", $_SERVER['SCRIPT_NAME']);

            return $base_url;
        }
    }

    public function generate_secret_key()
    {
        $random_key = md5(wp_rand(10, 99) . wp_rand(10, 99) . time() . wp_rand(10, 99));
        $secret_key = substr($random_key, 0, 8) . "-" . substr($random_key, 8, 8) . "-" . substr($random_key, 16, 8) . "-" . substr($random_key, 24, 8);

        return $secret_key;
    }

    public function SetFromPostData($isNew = false, $data = null)
    {
        $newData = [];

        $title = sanitize_text_field(ApbdWps_PostValue('title', ''));
        $connected_email = sanitize_email(ApbdWps_PostValue('connected_email', ''));
        $send_from = sanitize_text_field(ApbdWps_PostValue('send_from', ''));
        $from_email = sanitize_email(ApbdWps_PostValue('from_email', ''));
        $use_title = sanitize_text_field(ApbdWps_PostValue('use_title', ''));
        $attach_with = sanitize_text_field(ApbdWps_PostValue('attach_with', ''));
        $choose_category = absint(ApbdWps_PostValue('choose_category', ''));
        $privacy_policy = sanitize_text_field(ApbdWps_PostValue('privacy_policy', ''));
        $status = sanitize_text_field(ApbdWps_PostValue('status', ''));

        $send_from = in_array($send_from, array("C", "D")) ? $send_from : "C";
        $use_title = 'Y' === $use_title ? 'Y' : 'N';
        $attach_with = 'A' === $attach_with ? 'A' : 'I';
        $choose_category = strval($choose_category);
        $privacy_policy = 'Y' === $privacy_policy ? 'Y' : 'N';
        $status = 'A' === $status ? 'A' : 'I';

        $from_email = '';

        if (
            (1 > strlen($title)) ||
            (1 > strlen($connected_email))
        ) {
            return;
        }

        $newData['title'] = $title;
        $newData['connected_email'] = $connected_email;
        $newData['send_from'] = $send_from;
        $newData['from_email'] = $from_email;
        $newData['use_title'] = $use_title;
        $newData['attach_with'] = $attach_with;
        $newData['privacy_policy'] = $privacy_policy;
        $newData['status'] = $status;

        if ('A' === $attach_with) {
            if (empty($choose_category)) {
                return;
            }

            $newData['choose_category'] = $choose_category;
        }

        if ('Y' !== $privacy_policy) {
            $this->AddError("You must agree with the email to ticket terms and conditions.");
            return;
        }

        if ($isNew) {
            $is_duplicate = self::CheckDuplicate(null, $connected_email, $status);

            if (!$is_duplicate) {
                $secret_key = $this->generate_secret_key();

                if (! empty($email)) {
                    $newData['secret_key'] = $secret_key;
                } else {
                    $this->AddError("Something went wrong.");
                    return;
                }
            }
        }

        return parent::SetFromPostData($isNew, $newData);
    }

    /**
     * From version 1.4.4
     */
    static function UpdateDBTableCharset()
    {
        $thisObj = new static();
        $table_name = $thisObj->db->prefix . $thisObj->tableName;
        $charset = $thisObj->db->charset;
        $collate = $thisObj->db->collate;

        $alter_query = "ALTER TABLE `{$table_name}` CONVERT TO CHARACTER SET {$charset} COLLATE {$collate}";

        $thisObj->db->query($alter_query);
    }

    /**
     * From version 1.4.23
     */
    static function UpdateDBTable()
    {
        $thisObj = new static();

        $table = $thisObj->db->prefix . $thisObj->tableName;

        if ($thisObj->db->get_var("show tables like '{$table}'") == $table) {
            $thisObj->DBColumnAddOrModify('send_from', 'char', 1, '', 'NOT NULL', 'connected_email', 'radio(C=Connected,D=Default)');
            $thisObj->DBColumnAddOrModify('from_email', 'char', 255, '', 'NOT NULL', 'send_from');
            $thisObj->DBColumnAddOrModify('use_title', 'char', 1, '', 'NOT NULL', 'from_email', 'bool(Y=Yes,N=No)');
            $thisObj->db->query("UPDATE `{$table}` SET `send_from` = 'D'");
            $thisObj->db->query("UPDATE `{$table}` SET `use_title` = 'N'");
        }
    }

    static function CreateDBTable()
    {
        $thisObj = new static();
        $table = $thisObj->db->prefix . $thisObj->tableName;
        $charsetCollate = $thisObj->db->has_cap('collation') ? $thisObj->db->get_charset_collate() : '';

        if ($thisObj->db->get_var("show tables like '{$table}'") != $table) {
            $sql = "CREATE TABLE `{$table}` (
                `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
                `title` char(255) NOT NULL DEFAULT '',
                `email` char(255) NOT NULL DEFAULT '',
                `connected_email` char(255) NOT NULL DEFAULT '',
                `send_from` char(1) NOT NULL DEFAULT '' COMMENT 'radio(C=Connected,D=Default)',
                `from_email` char(255) NOT NULL DEFAULT '',
                `use_title` char(1) NOT NULL DEFAULT '' COMMENT 'bool(Y=Yes,N=No)',
                `attach_with` char(1) NOT NULL COMMENT 'bool(A=Active,I=Inactive)',
                `choose_category` char(255) NOT NULL,
                `privacy_policy` char(1) NOT NULL COMMENT 'bool(Y=Yes,N=No)',
                `secret_key` char(255) NOT NULL,
                `status` char(1) NOT NULL COMMENT 'bool(A=Active,I=Inactive)',
                PRIMARY KEY (`id`)
            ) $charsetCollate;";

            require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
            dbDelta($sql);
        }
    }

    function DropDBTable()
    {
        global $wpdb;

        $table_name = $wpdb->prefix . $this->tableName;
        $wpdb->query("DROP TABLE IF EXISTS `" . esc_sql($table_name) . "`");
    }

    static function DeleteById($id)
    {
        return parent::DeleteByKeyValue("id", $id);
    }

    static function CheckDuplicate($mailboxObj, $connected_email = '', $status = '', $id = 0)
    {
        $is_duplicate = false;

        $mailbox_id = absint($id);
        $mailbox_email = '';
        $mailbox_status = '';

        if (!empty($mailboxObj)) {
            $mailbox_email = sanitize_email($mailboxObj->connected_email);
            $mailbox_status = sanitize_text_field($mailboxObj->status);
        } elseif (!empty($connected_email)) {
            $mailbox_email = sanitize_email($connected_email);
            $mailbox_status = sanitize_text_field($status);
        }

        if (
            !empty($mailbox_email) &&
            ('A' === $mailbox_status)
        ) {
            $mainObj = new Mapbd_wps_imap_api_settings();
            $mainObj->connected_email($mailbox_email);
            $mainObj->id("!= '{$mailbox_id}'", true);
            $mainObj->status('A');

            if ($mainObj->Select()) {
                $is_duplicate = true;
            } else {
                $mainObj = new Mapbd_wps_imap_settings();
                $mainObj->user_email($mailbox_email);
                $mainObj->id("!= '{$mailbox_id}'", true);
                $mainObj->status('A');

                if ($mainObj->Select()) {
                    $is_duplicate = true;
                }
            }
        }

        return $is_duplicate;
    }
}
